### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by chen17-yixuan** [ybw0014/GlobalWarming-CN#7]
## Description (REQUIRED)

Version: GlobalWarming vBuild 5 zh-CN(ybw0014)
Issue: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "elem" is null

## Steps to reproduce the Issue (REQUIRED)

command pannel show

## Server Log

java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "elem" is null
        at me.poma123.globalwarming.guizhanlib.utils.JsonUtil.getFromPath(JsonUtil.java:34) ~[?:?]
        at me.poma123.globalwarming.guizhanlib.updater.UpdaterTask.getVersionFormat(UpdaterTask.java:69) ~[?:?]
        at me.poma123.globalwarming.guizhanlib.updater.UpdaterTask.run(UpdaterTask.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4011-Spigot-864e4ac-76931e8]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4011-Spigot-864e4ac-76931e8]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: 1.20.4
 - Slimefun Version: Slimefun-eabaa21-Beta

**Comment by ybw0014** [comment]
自动更新报错，不用管
